version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "chunkhound/maintainers"
    assignees:
      - "chunkhound/maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group updates to reduce PR noise
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "ruff*"
          - "mypy*"
        update-types:
          - "minor"
          - "patch"
      tree-sitter-dependencies:
        patterns:
          - "tree-sitter*"
        update-types:
          - "minor"
          - "patch"
      database-dependencies:
        patterns:
          - "duckdb*"
        update-types:
          - "patch"
    # Ignore certain dependencies that require manual review
    ignore:
      - dependency-name: "openai"
        update-types: ["version-update:semver-major"]
      - dependency-name: "duckdb"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tree-sitter*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "chunkhound/maintainers"
    assignees:
      - "chunkhound/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"