"""
Tests for site/scripts/sync-readme-positioning.mjs and the generated README block.

The script replaces only the marker-delimited positioning block in the root
README.md from the canonical site/src/lib/positioning.json; all surrounding
content is preserved byte-for-byte.
"""

import json
import pathlib
import subprocess
import tempfile

from tests.site.process_runner import run_text_process
from tests.site.tsx_runner import NPM, ROOT, sanitized_subprocess_env

SYNC_SCRIPT = ROOT / "site" / "scripts" / "sync-readme-positioning.mjs"
POSITIONING_FILE = ROOT / "site" / "src" / "lib" / "positioning.json"

BEGIN_MARKER = (
    "<!-- BEGIN POSITIONING: generated by site/scripts/sync-readme-positioning.mjs "
    "from site/src/lib/positioning.json -->"
)
END_MARKER = "<!-- END POSITIONING -->"

# The fake repo copies the real canonical file so the two can never drift.
POSITIONING_CONTENT = POSITIONING_FILE.read_text(encoding="utf-8")

SURROUNDING_PREFIX = "# ChunkHound\n\nIntro text.\n\n"
SURROUNDING_SUFFIX = "\n\n## Requirements\n\n- Python 3.10+\n"


def _stale_block() -> str:
    """A marker-delimited block with copy that does not match positioning.json."""
    return "\n".join(
        [
            BEGIN_MARKER,
            '<p align="center">',
            "  <strong>Old headline.</strong>",
            "</p>",
            "",
            '<p align="center">',
            "  Old subheadline.",
            "</p>",
            END_MARKER,
        ]
    )


def _make_fake_repo(tmp: str) -> pathlib.Path:
    """Create a fake repo with a canonical positioning.json and a stale README."""
    repo_root = pathlib.Path(tmp)
    lib_dir = repo_root / "site" / "src" / "lib"
    lib_dir.mkdir(parents=True)
    (lib_dir / "positioning.json").write_text(POSITIONING_CONTENT, encoding="utf-8")
    (repo_root / "README.md").write_text(
        SURROUNDING_PREFIX + _stale_block() + SURROUNDING_SUFFIX,
        encoding="utf-8",
    )
    return repo_root


def _make_repo_with_positioning(tmp: str, positioning: dict) -> pathlib.Path:
    """Fake repo with a custom positioning.json and a stale README."""
    repo_root = pathlib.Path(tmp)
    lib_dir = repo_root / "site" / "src" / "lib"
    lib_dir.mkdir(parents=True)
    (lib_dir / "positioning.json").write_text(
        json.dumps(positioning), encoding="utf-8"
    )
    (repo_root / "README.md").write_text(
        SURROUNDING_PREFIX + _stale_block() + SURROUNDING_SUFFIX,
        encoding="utf-8",
    )
    return repo_root


def _run_sync(repo_root: pathlib.Path, *extra: str) -> subprocess.CompletedProcess:
    """Run sync-readme-positioning.mjs against a fake repo directory."""
    env = sanitized_subprocess_env(CHUNKHOUND_ROOT=str(repo_root))
    return run_text_process(
        [NPM, "exec", "--prefix", "site", "--", "node", str(SYNC_SCRIPT), *extra],
        cwd=ROOT,
        env=env,
    )


def test_sync_replaces_block_and_preserves_surroundings() -> None:
    """Only the marker block changes; prefix/suffix survive byte-for-byte."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = _make_fake_repo(tmp)

        result = _run_sync(repo_root)
        assert result.returncode == 0, f"Script failed: {result.stderr}"

        readme = (repo_root / "README.md").read_text(encoding="utf-8")
        positioning = json.loads(POSITIONING_CONTENT)
        assert readme.startswith(SURROUNDING_PREFIX)
        assert readme.endswith(SURROUNDING_SUFFIX)
        assert f"<strong>{positioning['headline']}</strong>" in readme
        assert positioning["subheadline"] in readme
        assert positioning["amplifier"] in readme
        assert "Old headline." not in readme
        assert readme.count(BEGIN_MARKER) == 1
        assert readme.count(END_MARKER) == 1
        assert readme.index(BEGIN_MARKER) < readme.index(END_MARKER)


def test_sync_idempotent() -> None:
    """A second run leaves the synced README byte-identical."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = _make_fake_repo(tmp)
        _run_sync(repo_root)
        after_first = (repo_root / "README.md").read_text(encoding="utf-8")

        result = _run_sync(repo_root)
        assert result.returncode == 0, f"Script failed: {result.stderr}"
        assert (repo_root / "README.md").read_text(encoding="utf-8") == after_first


def test_sync_check_mode_detects_drift_without_writing() -> None:
    """--check exits non-zero on a stale block, zero after syncing, never writes."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = _make_fake_repo(tmp)

        result = _run_sync(repo_root, "--check")
        assert result.returncode != 0
        assert "out of sync" in result.stderr
        # Check mode must not have touched the stale README.
        assert "Old headline." in (repo_root / "README.md").read_text(encoding="utf-8")

        _run_sync(repo_root)
        result = _run_sync(repo_root, "--check")
        assert result.returncode == 0, result.stderr


def test_sync_missing_markers_errors() -> None:
    """README without positioning markers fails with an explicit error."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = pathlib.Path(tmp)
        (repo_root / "site" / "src" / "lib").mkdir(parents=True)
        (repo_root / "site" / "src" / "lib" / "positioning.json").write_text(
            POSITIONING_CONTENT, encoding="utf-8"
        )
        (repo_root / "README.md").write_text("# No markers here\n", encoding="utf-8")

        result = _run_sync(repo_root)
        assert result.returncode != 0
        assert "marker" in result.stderr.lower()


def test_sync_missing_positioning_source_errors() -> None:
    """Missing positioning.json fails with an explicit error."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = pathlib.Path(tmp)
        (repo_root / "README.md").write_text(
            f"{BEGIN_MARKER}\n{END_MARKER}", encoding="utf-8"
        )

        result = _run_sync(repo_root)
        assert result.returncode != 0
        assert "positioning.json" in result.stderr
        assert "not found" in result.stderr


def test_actual_readme_block_in_sync_with_canonical_positioning() -> None:
    """The real README block matches the generated canonical JSON output."""
    assert POSITIONING_FILE.exists(), f"Missing canonical source: {POSITIONING_FILE}"
    result = _run_sync(ROOT, "--check")
    assert result.returncode == 0, (
        f"README positioning block drifted from {POSITIONING_FILE}:\n{result.stderr}"
    )


def test_real_readme_contains_positioning_markers() -> None:
    """Guards against accidental marker removal: without them the drift test
    above passes vacuously (the sync script errors instead of checking)."""
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert BEGIN_MARKER in readme
    assert END_MARKER in readme
    assert readme.index(BEGIN_MARKER) < readme.index(END_MARKER)


def test_sync_duplicate_marker_block_errors() -> None:
    """A second BEGIN/END pair is ambiguous: abort rather than sync one block,
    and never mutate the README on a rejected run."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = _make_fake_repo(tmp)
        readme = (repo_root / "README.md").read_text(encoding="utf-8")
        duplicated = readme + "\n" + _stale_block()
        (repo_root / "README.md").write_text(duplicated, encoding="utf-8")

        result = _run_sync(repo_root)
        assert result.returncode != 0
        assert "exactly one" in result.stderr.lower()
        assert (repo_root / "README.md").read_text(encoding="utf-8") == duplicated


def test_sync_out_of_order_markers_error() -> None:
    """END before BEGIN is rejected with an explicit ordering error."""
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = pathlib.Path(tmp)
        lib_dir = repo_root / "site" / "src" / "lib"
        lib_dir.mkdir(parents=True)
        (lib_dir / "positioning.json").write_text(
            POSITIONING_CONTENT, encoding="utf-8"
        )
        (repo_root / "README.md").write_text(
            f"{END_MARKER}\n\n{BEGIN_MARKER}", encoding="utf-8"
        )

        result = _run_sync(repo_root)
        assert result.returncode != 0
        assert "out of order" in result.stderr.lower()


def test_sync_escapes_html_and_cannot_forge_end_marker() -> None:
    """`&`, `<`, `>` are escaped: a field can neither inject markup nor forge
    the END marker (`-->`) and corrupt the marker-delimited block."""
    hostile = {
        "headline": "Research & <review>",
        "subheadline": "Close --> then <!-- END POSITIONING --> inject",
        "amplifier": "a & b < c > d",
    }
    with tempfile.TemporaryDirectory() as tmp:
        repo_root = _make_repo_with_positioning(tmp, hostile)

        result = _run_sync(repo_root)
        assert result.returncode == 0, result.stderr

        readme = (repo_root / "README.md").read_text(encoding="utf-8")
        assert "Research &amp; &lt;review&gt;" in readme
        assert "a &amp; b &lt; c &gt; d" in readme
        # Raw markup must be neutralised, and the literal END marker text in a
        # field must be escaped rather than honored as a second delimiter.
        assert "<review>" not in readme
        assert readme.count(END_MARKER) == 1
