#!/usr/bin/env bash
# Generate docker-compose.yml and docker/nginx/mcp_upstream.conf for N chunkhound
# replicas.
#
# Plain `docker compose` (no Swarm) has no way to loop over N services with
# distinct per-replica bind mounts, so this script renders both files instead
# of hand-maintaining a fixed replica count. Re-run whenever --replicas
# changes; both outputs are gitignored — they're generated fresh on every
# deploy, never committed.
#
# Usage:
#   ./scripts/generate-compose.sh --replicas N   (default: 2)

set -euo pipefail

REPLICAS=2
while [ $# -gt 0 ]; do
    case "$1" in
        --replicas|-r)
            REPLICAS="$2"
            shift 2
            ;;
        *)
            echo "Usage: $0 [--replicas N]" >&2
            exit 1
            ;;
    esac
done

if ! [[ "$REPLICAS" =~ ^[0-9]+$ ]] || [ "$REPLICAS" -lt 1 ]; then
    echo "ERROR: --replicas must be a positive integer, got: $REPLICAS" >&2
    exit 1
fi

COMPOSE_FILE="docker-compose.yml"
UPSTREAM_FILE="docker/nginx/mcp_upstream.conf"

mkdir -p "$(dirname "$UPSTREAM_FILE")"

# ---- docker-compose.yml ----
{
cat <<'HEADER'
# Generated by scripts/generate-compose.sh — do not edit by hand.
# Re-run the generator (with the desired --replicas) to change replica count
# or pick up template changes.
version: "3.9"

# Shared config applied to every chunkhound replica.
x-chunkhound-common: &chunkhound-common
  image: chunkhound-mcp:latest
  build:
    context: .
    dockerfile: docker/Dockerfile
    args:
      HOST_UID: "${HOST_UID}"
      HOST_GID: "${HOST_GID}"
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '3.0'
  working_dir: ${CHUNKHOUND_SOURCE_PATH}
  env_file:
    - .env.docker
  environment:
    # DuckDB reconstructs the persistent HNSW index into memory on first DB open
    # — CPU-intensive for large DBs (~2 min, 600-800% CPU for 3-5M vectors).
    CHUNKHOUND_DB_EXECUTE_TIMEOUT: "7200"
    # Mount the host .chunkhound.json as the config source of truth.
    CHUNKHOUND_CONFIG_FILE: /etc/chunkhound/config.json
    # Match nginx proxy_read_timeout so long-running tools (code_research) don't get killed.
    SESSION_TIMEOUT: "1200000"
  networks:
    - mcp-net
  healthcheck:
    # Liveness-only: verify the HTTP transport is listening without creating an
    # MCP session. Omitting -f so curl exits 0 for any HTTP response (even 400);
    # it only fails on connection errors. Sending an initialize request here
    # would spawn a chunkhound child, hold the DuckDB exclusive lock for the
    # full sessionTimeout, and block the real MCP client.
    test: ["CMD-SHELL", "curl --max-time 3 --connect-timeout 3 -s -o /dev/null http://localhost:8080/mcp || exit 1"]
    interval: 30s
    timeout: 5s
    retries: 3
    start_period: 120s

services:
  # ── ChunkHound MCP replicas ─────────────────────────────────────────────────
  # Each replica mounts its own copy of the database.
  # DuckDB takes an exclusive write-lock on chunks.db at open time; sharing one
  # file across containers would cause all but the first to fail at startup.
  # Run scripts/prepare-db-replicas.sh once to populate each replica directory.
  #
  # NOTE: volumes are mounted read-write so DuckDB can write the WAL/lock files
  # it creates during normal open. With --read-only the lock is skipped, but the
  # WAL must be absent (a pending WAL blocks read-only open). Replicas are safe
  # because prepare-db-replicas.sh copies a clean DB without a WAL file.
  #
  # The .chunkhound.json config and Claude Code credentials are mounted
  # read-only from the SAME host paths into every replica — unlike chunks.db,
  # nothing locks or watches these, so there's no need to copy them per-replica.
HEADER

for i in $(seq 1 "$REPLICAS"); do
cat <<REPLICA

  chunkhound-${i}:
    <<: *chunkhound-common
    container_name: chunkhound-mcp-${i}
    volumes:
      - \${CHUNKHOUND_CONFIG_HOST_PATH}:/etc/chunkhound/config.json:ro
      - /opt/chunkhound/db/replica${i}:/data/db
      - \${CLAUDE_CLI_MODULE_PATH}:/usr/local/lib/node_modules/@anthropic-ai/claude-code:ro
      - \${CHUNKHOUND_SOURCE_PATH}:\${CHUNKHOUND_SOURCE_PATH}
      - \${CLAUDE_HOME_JSON_PATH}:/home/chunkhound/.claude.json:ro
      - \${CLAUDE_HOME_DIR_PATH}:/home/chunkhound/.claude:ro
REPLICA
done

cat <<'NGINX_HEADER'

  # ── nginx reverse proxy ─────────────────────────────────────────────────────
  nginx:
    image: nginx:1.27-alpine
    container_name: chunkhound-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      # Uncomment to add TLS termination (provide certs via additional volume):
      # - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/mcp_upstream.conf:/etc/nginx/conf.d/mcp_upstream.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mcp-net
    depends_on:
NGINX_HEADER

for i in $(seq 1 "$REPLICAS"); do
    echo "      chunkhound-${i}:"
    echo "        condition: service_healthy"
done

cat <<'FOOTER'

networks:
  mcp-net:
    driver: bridge
FOOTER
} > "$COMPOSE_FILE"

# ---- docker/nginx/mcp_upstream.conf ----
{
cat <<'UP_HEADER'
# Generated by scripts/generate-compose.sh — do not edit by hand.
upstream chunkhound_backends {
    # Route by client IP so all requests from a given client (initialize +
    # all subsequent tool calls) always reach the same backend. This is
    # required because the StreamableHTTP session manager is stateful per
    # process and DuckDB holds an exclusive lock per process.
    #
    # hash $http_mcp_session_id was tried first but fails: the initialize
    # request has no session ID yet, so it hashes "" and lands on backend A;
    # subsequent requests hash the real session UUID and may land on backend B
    # which returns 400 "No valid session ID". ip_hash avoids this by tying
    # all requests from one client to one backend before any session exists.
    hash $remote_addr consistent;

UP_HEADER

for i in $(seq 1 "$REPLICAS"); do
    echo "    server chunkhound-${i}:8080;"
done

cat <<'UP_FOOTER'

    # Reuse upstream connections to reduce handshake overhead.
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://chunkhound_backends;

        # HTTP/1.1 keep-alive — NOT a WebSocket upgrade.
        # streamableHttp uses plain HTTP with SSE for server-to-client streaming.
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # MCP streamableHttp requires Accept: application/json, text/event-stream.
        # Claude Code omits text/event-stream, which causes the MCP SDK to reject
        # the request with 406. Override here so the backend always sees the right header.
        proxy_set_header Accept            "application/json, text/event-stream";

        # SSE streaming requires no buffering — without this nginx will hold the
        # response until the buffer fills, breaking real-time tool call updates.
        proxy_buffering           off;
        proxy_cache               off;
        chunked_transfer_encoding on;

        proxy_read_timeout 1200s;
        proxy_send_timeout 1200s;
    }

    # Lightweight liveness probe — does not count as MCP traffic.
    location /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
UP_FOOTER
} > "$UPSTREAM_FILE"

echo "Generated ${COMPOSE_FILE} and ${UPSTREAM_FILE} for ${REPLICAS} replica(s)."
