"""Extract chunkhound_native from the maturin wheel into the active venv.

Also writes the same files into the source tree's chunkhound_native/ (and
any wheel-repair *.libs/ sibling directory) -- the source tree is a real
package too (installed editable), and Python resolves it ahead of
site-packages on sys.path, so leaving it untouched would make this script
silently install a build that never actually gets imported.
"""

import pathlib
import subprocess
import sys
import sysconfig
import zipfile


def _is_dirty(repo_root: pathlib.Path, relative_path: str) -> bool:
    """True if `relative_path` has uncommitted changes in the repo's git tree.

    Any non-zero exit is treated as dirty (fail safe): git errors (e.g. rc=128
    when outside a git repo, shallow checkout, or missing HEAD) mean we cannot
    prove the file is clean, so refuse to overwrite it rather than clobbering
    a potential local edit. In tarball / non-git contexts this aborts
    intentionally -- fail closed.
    """
    try:
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", "--", relative_path],
            cwd=repo_root,
            capture_output=True,
        )
        if tracked.returncode != 0:
            return True
        result = subprocess.run(
            ["git", "diff", "--quiet", "HEAD", "--", relative_path],
            cwd=repo_root,
        )
        return result.returncode != 0
    except FileNotFoundError:
        # git not on PATH -- cannot prove clean, fail closed like rc=128
        return True


def _is_extension(name: str) -> bool:
    """Return whether `name` is a compiled native-extension wheel entry."""
    return name.startswith("chunkhound_native/") and (
        name.endswith(".so") or name.endswith(".pyd")
    )


def _is_generated_artifact(name: str) -> bool:
    """Return whether `name` is regenerated by the native wheel build."""
    return _is_extension(name) or name.split("/", 1)[0].endswith(".libs")


def _is_safe_member(name: str) -> bool:
    """Return whether a wheel member stays beneath each extraction root."""
    parts = name.split("/")
    return (
        bool(name)
        and "\\" not in name
        and "\x00" not in name
        and not pathlib.PureWindowsPath(name).drive
        and all(part not in ("", ".", "..") for part in parts)
    )


def _select_files(names: list[str]) -> list[str]:
    """Return only the wheel entries that install_native.py should extract.

    Wheel-repair tools (auditwheel/delocate/delvewheel) bundle shared
    libraries the extension depends on (e.g. DuckDB) into a sibling
    "<pkg>.libs/" directory alongside the package, not inside it.

    dist-info and other metadata entries are deliberately excluded --
    install_native.py must not overwrite the dist-info of an already-
    installed PyPI version, or uv run's auto-sync will reinstall that
    PyPI wheel and revert the local build.
    """
    return [
        name
        for name in names
        if not name.endswith("/")
        and (_is_generated_artifact(name) or name == "chunkhound_native/__init__.py")
    ]


def _validate_members(names: list[str]) -> None:
    """Reject wheel members that could escape an extraction root.

    Runs on the FULL wheel namelist, not just the selected files: a member
    that _select_files would silently skip (e.g. an absolute-path .so) is
    still rejected explicitly instead of being ignored, matching the repo's
    fail-closed philosophy.
    """
    unsafe = next(
        (
            name
            for name in names
            if not name.endswith("/") and not _is_safe_member(name)
        ),
        None,
    )
    if unsafe is not None:
        sys.exit(f"Unsafe wheel member {unsafe!r} -- refusing to extract wheel")


def _require_extension(wheel_path: pathlib.Path, selected: list[str]) -> None:
    """Reject wheels that would leave a previously built extension in place."""
    if not any(_is_extension(name) for name in selected):
        sys.exit(
            f"No extension files (.so/.pyd) found in {wheel_path.name} -- "
            "refusing to install a stale or foreign wheel (clear "
            "target/wheels/ and rerun 'maturin build --out target/wheels/')"
        )


def _guard_source_file(
    dest: pathlib.Path, data: bytes, repo_root: pathlib.Path, name: str
) -> None:
    """Refuse to replace a changed hand-editable source-tree file."""
    if (
        dest.exists()
        and dest.read_bytes() != data
        and not _is_generated_artifact(name)
        and _is_dirty(repo_root, name)
    ):
        sys.exit(
            f"{dest} has uncommitted changes that differ from this build -- "
            "commit or stash it first, or you'll lose those edits."
        )


def _install_member(
    archive: zipfile.ZipFile,
    name: str,
    destinations: list[pathlib.Path],
    repo_root: pathlib.Path,
) -> None:
    """Atomically install one validated wheel member to every destination."""
    data = archive.read(name)
    for dest_root in destinations:
        dest = dest_root / name
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest_root == repo_root:
            _guard_source_file(dest, data, repo_root, name)
        tmp = dest.parent / (dest.name + ".tmp")
        tmp.write_bytes(data)
        tmp.replace(dest)


def extract_from_wheel(
    wheel_path: pathlib.Path,
    destinations: list[pathlib.Path],
    repo_root: pathlib.Path,
) -> int:
    """Extract the compiled extension files from `wheel_path` into each
    directory in `destinations` (typically the source tree and site-packages).

    - Only `.so`/`.pyd`, `__init__.py`, and `*.libs/` files are extracted;
      dist-info and all other wheel entries are skipped (see
      `_select_files` for the version-conflict rationale).
    - Files are written to a temp file and atomically renamed into place
      (POSIX atomic; Windows replace is not strictly atomic but still avoids
      hardlink cache poisoning): `dest` may be hardlinked into uv's shared
      package cache (uv links from cache whenever cache and target share a
      filesystem), so writing content in place would corrupt that shared inode
      for every other venv sharing the cache.
    - The source tree's `__init__.py` is hand-editable (unlike generated
      extension and runtime artifacts) -- if it differs from the wheel and
      has uncommitted changes, the script refuses to clobber it.
    - Exits with an error when the wheel contains no extension files: a wheel
      without .so/.pyd is always broken for this script, so fail closed rather
      than silently "installing" nothing (which would leave `make dev` with a
      stale native extension).

    Returns the number of wheel entries selected (installed into each
    destination).
    """
    with zipfile.ZipFile(wheel_path) as archive:
        names = archive.namelist()
        _validate_members(names)
        selected = _select_files(names)
        _require_extension(wheel_path, selected)
        for name in selected:
            _install_member(archive, name, destinations, repo_root)
    return len(selected)


def find_wheels(wheels_dir: pathlib.Path) -> list[pathlib.Path]:
    """Find and validate the wheel to install from `wheels_dir`."""
    wheels = sorted(wheels_dir.glob("chunkhound*.whl"))
    if not wheels:
        sys.exit(
            "No wheel found in target/wheels/ -- run "
            "'maturin build --out target/wheels/' first "
            "(add --release for dev-release)"
        )
    if len(wheels) > 1:
        names = "\n  ".join(str(w) for w in wheels)
        sys.exit(
            f"Multiple wheels found in target/wheels/ -- clear the "
            f"directory before rebuilding:\n  {names}"
        )
    return wheels


def main() -> None:
    wheels = find_wheels(pathlib.Path("target/wheels"))
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    site = pathlib.Path(sysconfig.get_path("platlib"))
    if not site.exists():
        sys.exit(f"site-packages not found at {site}")

    destinations = [repo_root, site]
    installed_count = extract_from_wheel(wheels[-1], destinations, repo_root)
    print(
        f"Installed {installed_count} selected wheel entries from {wheels[-1].name} "
        f"into {len(destinations)} locations"
    )


if __name__ == "__main__":
    main()
