import type { ConfiguratorRequirement } from "./types.ts";
import {
  ANTHROPIC_SVG,
  CURSOR_SVG,
  DEEPSEEK_SVG,
  GEMINI_SVG,
  GROK_SVG,
  OLLAMA_SVG,
  OPENAI_SVG,
  OPENCODE_SVG,
  OPENROUTER_SVG,
  ORCAROUTER_SVG,
  PI_SVG,
  ROO_CODE_SVG,
  VERCEL_SVG,
  VLLM_SVG,
  VOYAGEAI_SVG,
  VSCODE_SVG,
  WINDSURF_SVG,
  ZED_SVG,
} from "./icons.ts";

export const requirements = {
  pi: {
    id: "pi",
    label: "pi-mcp-adapter",
    url: "https://pi.dev/packages/pi-mcp-adapter",
    svg: PI_SVG,
  },
  cursor: {
    id: "cursor",
    label: "Cursor with MCP support",
    url: "https://cursor.com/docs/mcp",
    svg: CURSOR_SVG,
  },
  claudeCode: {
    id: "claude-code",
    label: "Claude Code CLI (signed in)",
    url: "https://code.claude.com/docs/en/mcp",
    svg: ANTHROPIC_SVG,
  },
  vscode: {
    id: "vscode",
    label: "VS Code with MCP support",
    url: "https://code.visualstudio.com/docs/agent-customization/mcp-servers",
    svg: VSCODE_SVG,
  },
  opencode: {
    id: "opencode",
    label: "OpenCode CLI (signed in)",
    url: "https://opencode.ai/docs/cli/",
    svg: OPENCODE_SVG,
  },
  codex: {
    id: "codex",
    label: "Codex CLI (signed in)",
    url: "https://learn.chatgpt.com/docs/codex/cli",
    svg: OPENAI_SVG,
  },
  windsurf: {
    id: "windsurf",
    label: "Windsurf with MCP support",
    url: "https://docs.devin.ai/desktop/cascade/mcp",
    svg: WINDSURF_SVG,
  },
  rooCode: {
    id: "roo-code",
    label: "Roo Code extension",
    url: "https://roocodeinc.github.io/Roo-Code/features/mcp/using-mcp-in-roo/",
    svg: ROO_CODE_SVG,
  },
  zed: {
    id: "zed",
    label: "Zed with MCP support",
    url: "https://zed.dev/docs/ai/mcp",
    svg: ZED_SVG,
  },
  voyageApiKey: {
    id: "voyage-api-key",
    label: "VoyageAI API key",
    url: "https://dashboard.voyageai.com/api-keys",
    svg: VOYAGEAI_SVG,
  },
  voyageTrainingOptOut: {
    id: "voyage-training-opt-out",
    label: "Opt out of VoyageAI training for true privacy",
    url: "https://dashboard.voyageai.com/organization/tos",
    svg: VOYAGEAI_SVG,
    optional: true,
  },
  openaiApiKey: {
    id: "openai-api-key",
    label: "OpenAI API key",
    url: "https://platform.openai.com/api-keys",
    svg: OPENAI_SVG,
  },
  ollama: {
    id: "ollama",
    label: "Ollama",
    url: "https://ollama.com/download",
    svg: OLLAMA_SVG,
  },
  ollamaEmbedModel: {
    id: "ollama-embed-model",
    label: "qwen3-embedding model",
    url: "https://ollama.com/library/qwen3-embedding",
    svg: OLLAMA_SVG,
  },
  vllm: {
    id: "vllm",
    label: "vLLM",
    url: "https://docs.vllm.ai/en/latest/",
    svg: VLLM_SVG,
  },
  vllmEmbedEndpoints: {
    id: "vllm-embed-endpoints",
    label: "Qwen3 embedding + reranker endpoints",
    url: "https://docs.vllm.ai/en/latest/",
    svg: VLLM_SVG,
  },
  anthropicApiKey: {
    id: "anthropic-api-key",
    label: "Anthropic API key",
    url: "https://console.anthropic.com/settings/keys",
    svg: ANTHROPIC_SVG,
  },
  geminiApiKey: {
    id: "gemini-api-key",
    label: "Gemini API key",
    url: "https://aistudio.google.com/api-keys",
    svg: GEMINI_SVG,
  },
  deepseekApiKey: {
    id: "deepseek-api-key",
    label: "DeepSeek API key",
    url: "https://platform.deepseek.com/api_keys",
    svg: DEEPSEEK_SVG,
  },
  grokApiKey: {
    id: "grok-api-key",
    label: "xAI API key",
    url: "https://console.x.ai/team/default/api-keys",
    svg: GROK_SVG,
  },
  ollamaLlmModel: {
    id: "ollama-llm-model",
    label: "qwen3-coder:30b model",
    url: "https://ollama.com/library/qwen3-coder",
    svg: OLLAMA_SVG,
  },
  vllmLlmModel: {
    id: "vllm-llm-model",
    label: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    url: "https://docs.vllm.ai/en/latest/",
    svg: VLLM_SVG,
  },
  openrouterApiKey: {
    id: "openrouter-api-key",
    label: "OpenRouter API key",
    url: "https://openrouter.ai/keys",
    svg: OPENROUTER_SVG,
  },
  vercelApiKey: {
    id: "vercel-api-key",
    label: "Vercel AI Gateway API key",
    url: "https://vercel.com/d?to=%2F%5Bteam%5D%2F%7E%2Fai-gateway%2Fapi-keys&title=AI+Gateway+API+Keys",
    svg: VERCEL_SVG,
  },
  orcarouterApiKey: {
    id: "orcarouter-api-key",
    label: "OrcaRouter API key",
    url: "https://www.orcarouter.ai",
    svg: ORCAROUTER_SVG,
  },
} satisfies Record<string, ConfiguratorRequirement>;
