name: Full Test Suite (Nightly)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  full-test-suite:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync
        
      - name: Run linting
        run: uv run ruff check chunkhound
        
      - name: Run type checking
        run: uv run mypy chunkhound
        
      - name: Run full test suite
        run: uv run pytest tests/ -v
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results.xml
            .coverage
          retention-days: 7